src/protocolsupport/protocol/v_1_5/remappers/ItemIDRemapper.java
Fixes 1.5.2 crash when viewing a nametag, but I didn't test.
EDIT: Tested, 1.5.2 Client doesn't crash anymore.
=> Remap 421 (Nametag) to 1 (Stone)

src/protocolsupport/protocol/transformer/v_1_5/serverboundtransformer/PlayPacketTransformer.java, src/protocolsupport/protocol/transformer/v_1_6/serverboundtransformer/PlayPacketTransformer.java
Fixed:
* Missing client disconnect packet for 1.5.2 - 1.6.4
Fix based on: 
MCP 1.8 -> Client -> net.minecraft.client.multiplayer.WorldClient: sendQuittingDisconnectingPacket()
=> Fix miss disconnect packet for 1.5.2 - 1.6.4

src/protocolsupport/protocol/transformer/mcpe/packet/mcpe/both/ChatPacket.java
Fixed:
- Instead of text shows the player's nickname.
Before: https://www.dropbox.com/s/bvoyrvbk3mpv9m0/before.jpg
After:https://www.dropbox.com/s/ean94fssovnodl8/after.jpg
=> Fix chat message

src/protocolsupport/protocol/typeremapper/id/IdRemapper.java
New block remappings for MCPE.
Almost every block (not item, I will do the item remapping when item remapping is working for the MCPE client, so I can test it) remapping is done for MCPE.
Also, some blocks can't be remapped (example: Podzol: MC 1.8.8 ID: 3:1; MCPE ID: 243) and some maybe missing or wrong.
The problem is that the client desyncs from the server a lot, walking? desync. viewing a unremapped block? desync. doing nothing? desync. (And, when it does desync, the only fix is disconnecting the client and kicking it from the console), maybe those desyncs will be fixed as the mcpe branch goes more stable and feature complete :smile: 
Also, IDs are different, I was getting (and comparing) every ID on Minecraft Wiki, however, then I found that some IDs are wrong (when comparing in the …
=> [MCPE] Update (and add new) block remappings for MCPE.

src/protocolsupport/protocol/typeremapper/id/IdRemapper.java
Remove (almost) every redstone remapping.
Change some blocks to new remappings (jukebox > noteblock (instead of wood))
=> [MCPE] Update MCPE Remappers for 0.13.X

src/protocolsupport/ProtocolSupport.java, src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleSpawnLiving.java, src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleSpawnObject.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_1_7/EntityTeleport.java, src/protocolsupport/protocol/typeremapper/watchedentity/WatchedDataRemapper.java, src/protocolsupport/protocol/typeremapper/watchedentity/remapper/SpecificRemapper.java, src/protocolsupport/protocol/typeremapper/watchedentity/types/WatchedEntity.java, src/protocolsupport/protocol/typeremapper/watchedentity/types/WatchedLiving.java, src/protocolsupport/protocol/typeremapper/watchedentity/types/WatchedObject.java, src/protocolsupport/protocol/typeremapper/watchedentity/types/WatchedPlayer.java, src/protocolsupport/protocol/typeremapper/watchedentity/types/WatchedType.java
Already makes things less awkward.
For now the SpecificRemapper just transforms from WatchedType crudely and the metadata remapper still uses the SpecificRemapper, but that remapper has to be changed anyway.
I just copied most of the values of the SpecificRemapper, and added a few bukkit types.
=> Schism of SpecificRemapper and WatchedType

src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleSpawnObject.java, src/protocolsupport/protocol/typeremapper/watchedentity/types/WatchedObject.java, src/protocolsupport/protocol/typeremapper/watchedentity/types/WatchedType.java
Since minecarts are the only entities that on the network side that are divided using objectData, its done with a bit of a hack by just giving them high id's.
Objects which have different networking ids can now also be found using their corresponding bukkit id using a different function.
=> [WatchedType] Fixed networkIds, improved bukkit and minecart support

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnExpOrb.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnGlobal.java, src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java
To avoid code redundancy I created a static method in SpawnGlobal since the code used in XP orbs and lightning are the same. (except the entity type)
However this may or may not be a problem when entity metadata is implemented. (since, according to @DaMatrix, the XP count for XP orbs are sent in the metadata (instead of PC where it is sent in the SpawnExpOrb packet))
=> Implement "SpawnExpOrb" packet

resources/plugin.yml, src/protocolsupport/ProtocolSupport.java, src/protocolsupport/commands/CommandHandler.java
CommandHandler:
- Moved (args.length == 1) into one enclosing if statement
- Added proper usage message in case of invalid command. onCommand now
always returns true.
- Added checks for new config values (see below)
ProtocolSupport:
- Added two config values
- expose-plugin if set to false will send unknown command message if
someone without permission attempts to execute /ps to avoid exposure of
the plugin if wanted. default value is true (send "no power" message)
- list-only-relevant-versions if set to true will only list versions
that have connected players in /ps list ; default value is false (list
all versions regardless)
These changes should make ProtocolSupport commands more accessible to
users without programming knowledge.
=> /protocolsupport command improvements

src/protocolsupport/protocol/typeremapper/watchedentity/remapper/SpecificRemapper.java
This simple patch fixes derpy snowmen. Tested in 1.12 and 1.9.
> Changed boolean to byte for noHat Snowmen. This is necessary because for some reason Mojang choose > this property to be send as the fifth bit in a byte.
At first I thought this was just an issue with Spigot. So I reported in on [there](https://hub.spigotmc.org/jira/browse/SPIGOT-3417).
It turned out that they lacked an event caller, but the snowmen not showing was a result of ProtocolSupport. I am working on remapping all the values for PSPE, that's why I cought it. 
But really, we shouldn't forget the derpy snowmen! 😉
=> [Patch] Fix for derpy snowman.

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/WorldCustomSound.java, src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java, src/protocolsupport/protocol/typeremapper/pe/PEPacketIDs.java
Something that I did a long time ago but wasn't working due to the [missing resource pack handshake](https://github.com/ProtocolSupport/ProtocolSupport/pull/566).
Sounds still need to be remapped to their PE counterparts, but using `/playsound camera.take_picture master Steve 0 64 0` (or any other PE sound) plays the sound without any issues. 😉
=> Implement "WorldCustomSound" packet

src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java, src/protocolsupport/protocol/typeremapper/itemstack/fromclient/MonsterEggFromLegacyIdRemapper.java
Converts legacy (data value based) spawn eggs to modern (NBT based) spawn eggs.
Fixes issues when getting spawn eggs from creative in pre-1.9 clients.
The data value is also stripped out when converting to modern spawn eggs.
(Spawn egg from 1.8, given to a 1.12 client)
=> Convert legacy IDs spawn eggs from creative mode to modern NBT based spawn eggs

src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/Chat.java
**This field should be checked in IDA to see what is its real purpose.**
It seems 1.2 added a new (unknown) field in the Chat packet.
After debugging a little bit, this string is always empty no matter what I did.
```
[18:45:42 INFO]: ???:
[18:45:42 INFO]: sender: MrPowerGamerBR
[18:45:42 INFO]: message: test test test
[18:45:42 INFO]: <MrPowerGamerBR> test test test
```
=> Skip unknown string on Chat

src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleChat.java, src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/Chat.java, src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/CommandRequest.java, src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketDecoder.java, src/protocolsupport/protocol/typeremapper/pe/PEPacketIDs.java
This implements the "Request Command" packet, which, since 1.2, allows commands not sent via the available command packet to be executed.
While this code works:tm:, the code within `MiddleChat#create(...)` is so protocol dependent that it almost hurts inside when reading it, I tried finding any other examples of other MiddleXYZ packets that has that method implement but almost none of them has it. (and the ones that has it doesn't need the version object) so I wonder if that's the proper way to do it. 👍
Anyway, this reads the request command packet and creates a MiddleChat packet for the server to process.
This commit also removes the old command prefixes `mcpenew` branch had to execute commands, since this commit obsoletes that old "hack".
=> Add command support using slashes, remove old command prefixes

src/protocolsupport/protocol/typeremapper/tileentity/TileNBTRemapper.java
(for @7kasper)
Since 1.2 MCPE uses the "Text" tag to save the NBT data to disk, it also uses for client -> server sign updates. It seems the old tags are only used for backward compat
=> [PSPE] [Meta&Tiles] Use new lines for sign text

src/protocolsupport/api/ProtocolVersion.java
Avoid MessageFormat.format call in protocolsupport.api.ProtocolVersion.OrderId.compareTo because it produces huge amounts of characters (600kB/player/second on our spigot servers). Maybe a simple "Cant compare order from different types" or "Cant compare order from different types: this - " + type + ", other - " + o.type will be sufficient to avoid the format call.
Image shows 5 Minutes of jmc Flight Recording on ~10 Player Spigot server.
=> Avoid gc stressing MessageFormat.format call

src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java, src/protocolsupport/protocol/typeremapper/itemstack/toclient/ItemIdToPEIdSpecificRemapper.java, src/protocolsupport/protocol/typeremapper/pe/PEDataValues.java
Updates the block remapper for MCPE 1.2
This PR also adds a item remapper, because Mojang loves changing the item IDs to differ from PC -> PE.
=> Update remappers for MCPE 1.2

src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java, src/protocolsupport/protocol/typeremapper/itemstack/toclient/PotionToPEIdSpecificRemapper.java
Lingering potions aren't remapped yet, they seem to use NBT tags but I couldn't find anything related to that. :/
=> Remap Potion/Splash Potion to PE IDs

src/protocolsupport/zplatform/impl/glowstone/injector/GlowStoneNettyInjector.java, src/protocolsupport/zplatform/impl/spigot/injector/network/SpigotNettyInjector.java
this change makes the raknet server start on the same ip/interface as the one defined in the config file of the server.
=> [PSPE] start the raknet server on the same ip as the mc server

src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleChat.java, src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleCollectEffect.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Title.java, src/protocolsupport/protocol/storage/NetworkDataCache.java
The important stuff here is the subtitle updating packet.
Before this commit, if a plugin (or if you used `/title`) did this
`player.sendTitle("hello", "world", 20, 60, 20);`
The client would only show "hello"
If, after sending that, you did this
`player.sendTitle("ProtocolSupportPE", "is awesome!", 20, 60, 20);`
the client would show "ProtocolSupportPE" and "world"
This commit fixes that by sending a title packet after the subtitle packet, however I also needed to do some calculations to figure out if the title is still visible on the PE client, to avoid visible titles when using commands that should not display a new title, like `/title player subtitle`
The only minor inconvenience with this commit is that, if you update the subtitle while the title is already visible on screen, the …
=> Fix "Can't compare order from different types", fix subtitle updating for MCPE clients

build.gradle
Updated Glowstone from `2017.9.0` (1.12.1) to `2017.10.0` (1.12.2).
Looks like if you use a library for an older version, the compiler will 'cache' the server version (here: `GlowServer.GAME_VERSION`) instead of getting the actual version from the server. This means that using the latest ProtocolSupport with the latest Glowstone build will shutdown the server because the plugin thinks the version is 1.12.1 even though the server is on 1.12.2.
I don't know about gradle, but in Maven I think the `<scope>runtime</scope>` dependency tag would prevent this. Or maybe reflection would be more appropriate here.
=> Update Glowstone version to latest to support 1.12.2.

src/protocolsupport/protocol/serializer/ItemStackSerializer.java, src/protocolsupport/protocol/typeremapper/pe/PEDataValues.java
I tested, and it works:tm:
It creates a new remap table with the "reversed" values, containing the PE -> PC IDs.
=> Add "revert remap" when reading the ItemStack from the client, fixes remapped items from creative for PE clients

src/protocolsupport/protocol/typeremapper/id/IdRemapper.java
Fixes the remap of the boneblock.
Currently for 1.8 and 1.9 clients it is air.
Currently (1.12.2 client):
Currently (1.8.9 client):
=> Fix boneblock remap

src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java
Same thing as last time, just for the itemstack.
(Missed that last time)
=> Fix Boneblock ItemStack remap

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Position.java, src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/PositionLook.java, src/protocolsupport/protocol/storage/NetworkDataCache.java
The problem: PE sends rounded positions (based on the change it does itself). This is really irritating as it intersects with boundingboxes or so the server thinks.
The way the fix works is it fakes a position apology to the server if the server sends a teleport that is within the leniency. This leniency is standard 0.5 blocks, which makes you just able to walk up a halfslab. When running up stairs of any sort (halfstairs, stairs cakeblocks etc etc), however, you sometimes skim through the BB of that for more than 0.5 blocks. So when you are moving up, the leniency of the position is set to 3 blocks.
=> [PSPE] Fix for BB & rounded position collision :wink:

src/protocolsupport/protocol/packet/handler/AbstractLoginListener.java, src/protocolsupport/zplatform/PlatformUtils.java, src/protocolsupport/zplatform/impl/glowstone/GlowStoneMiscUtils.java, src/protocolsupport/zplatform/impl/glowstone/injector/GlowStoneServerConnectionChannel.java, src/protocolsupport/zplatform/impl/glowstone/network/GlowStoneChannelHandlers.java, src/protocolsupport/zplatform/impl/spigot/SpigotMiscUtils.java
It looks like encryption was only working for the Spigot pipeline, so I added a check for Glowstone and replicated the correct order for GS's channel pipeline.
~After this fix, a client receiving a chat packet (0x0F), like the join message, will crash. I'm not sure if this is caused by this particular fix or by another issue in ProtocolSupport.~ This is fixed, I swapped the encryption/decryption modes by accident.
=> Fix encryption in pipeline for Glowstone

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_4_5_6_7_8_9r1_9r2_10_11_12r1_12r2/TimeUpdate.java
Flicker problem is in 1.5.2 too.
and 1.6.4 or later is not
=> Use abs time in <= 1.5.2

src/protocolsupport/zplatform/impl/spigot/entitytracker/SpigotEntityTrackerEntry.java
Is this a crime?
----
The stuttering arrows and other objects are quite annoying, especially in PVP.
Since PE doesn't do motion (except for ItemEntities) the only solution is to send positions more often.
The server does this already for most mobs, but objects usually have a pesky updateInterval to save performance. So, why not just send movement updates always when there is a good velocity? 😉 
Perhaps we can optimise it a bit more, or maybe not 🤷‍♂️
=> Possible solution for stuttering objects.

src/protocolsupport/zplatform/impl/spigot/entitytracker/SpigotEntityTrackerBlock.java, src/protocolsupport/zplatform/impl/spigot/injector/SpigotEntityTrackerInjector.java
Sends block break animations to PE player if it is the one mining the block too. This way the faker can catch the block break animation.
=> [PSPE] Possible fix for block break animations.

src/protocolsupport/ProtocolSupport.java
New attempt, in correct branch and recommended placement.
=> Set java.awt.headless to true to disable app window on macos

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/TimeUpdate.java
First `worldAge` is wrong. It will led time past when dodaylightcycle=false.
Spigot flip the time when do dodaylightcycle false. PE has different behevior with PC when time < 0. So we need flip it again.
```
public PacketPlayOutUpdateTime(long var1, long var3, boolean var5) {
this.a = var1;
this.b = var3;
if (!var5) {
this.b = -this.b;
if (this.b == 0L) {
this.b = -1L;
}
}
}
```
=> Fix pe time update when dodaylightcycle false

build.gradle
(Related #787)
This builds the jar to the normal Gradle output directory (with normal project name and version suffix) and copies it after it to target/ProtocolSupport.jar (without version suffix).
JitPack builds:
[Build log](https://jitpack.io/com/github/games647/ProtocolSupport/jitpack-7c18ea65ca-1/build.log)
[Output jar](https://jitpack.io/com/github/games647/ProtocolSupport/jitpack-7c18ea65ca-1/ProtocolSupport-jitpack-7c18ea65ca-1.jar)
Other project can then use something like this.
```xml
<repositories>
<repository>
<id>jitpack.io</id>
<url>https://jitpack.io</url>
</repository>
</repositories>
```
```xml
<dependency>
<groupId>com.github.games647</groupId>
<artifactId>ProtocolSupport</artifactId>
<version>jitpack-7c18ea65ca-1</version>
</dependency>
```
For versioning you could tag …
=> Allow JitPack to find the output jar by copying it

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_4_5_6_7_8/WorldCustomSound.java
If name size more than 32, would be crash in 1.4.7 & 1.5.2. but 1.6 or higher isn't.
Is this correct way for solve that?
=> Sound name size make to <= 32

src/protocolsupport/protocol/typeremapper/pe/PEDataValues.java
The names of the fields in PEEntityData must match exactly the format in entitydata.json, including case.
Without this fix, the information in entitydata.json is basically lost.
=> GSON fails to match PEEntityData fields from entitydata.json

resources/resources/pe/entitydata.json, src/protocolsupport/ProtocolSupport.java, src/protocolsupport/protocol/typeremapper/watchedentity/remapper/SpecificRemapper.java
Also print warning if bounding box is missing from json for future problems like this.
Fixes PSPS#77.
=> Fix bounding box for ender dragon

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnLiving.java, src/protocolsupport/protocol/typeremapper/pe/PEDataValues.java
Unfortunately, I've not yet been able to determine correct IDs for all types. But without any mapping at all, we crash with NPE when the entity spawn. :(
=> Add missing PE entity IDs for new mobs (fish varietes, etc).

src/protocolsupport/protocol/typeremapper/block/LegacyBlockData.java
Also improve handling of carved/plain pumpkins (but directions are still wrong).
=> Fix legacy block states for melon/pumpkin stems and brick stairs.

resources/resources/mappings/preflatteningblockiddata.json, src/protocolsupport/protocol/typeremapper/block/LegacyBlockData.java
This resolves the last of the remaining blocks listed in #898 
Namely oak_wood, spruce_wood, jungle_wood, birch_wood, acacia_wood, dark_oak_wood, stone_slab, brick_slab, stone_brick_slab, nether_brick_slab, quartz_slab, purpur_slab, nether_brick_fence and red_mushroom_block.
Also allows stripped wood blocks to be remapped, though not directly added here.
=> Fixes some mappings for pre-existing blocks

resources/resources/pe/entitydata.json, resources/resources/pe/entitydata_inventory.json, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/InventoryOpen.java, src/protocolsupport/protocol/typeremapper/pe/PEDataValues.java
Fix incorrect bounding boxes, and make entitydata JSON easier to update in the future.
* Break out the InventoryFilter from entitydata.json and PEEntityData into entitydata_inventory.json and PEEntityInventoryData. (The filter part does not validate as correct json, which prohibited use by json tools like jq).
* Sort and normalize the json in entitydata.json and entitydata_inventory.json.
* Update entitydata.json with correct values for turtle, parrot and wither skeleton.
Note that the InventoryFilter part seems to not work at the moment, so future cleanup/fixes to this will certainly be needed. For now, I just kept the code as similar as possible while splitting into a separate class.
=> Entity json data cleanup and bounding box fixes

src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleAnimation.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleBlockDig.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleBlockPlace.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleChat.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleClientSettings.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleCreativeSetSlot.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleCustomPayload.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleEntityAction.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleHeldSlot.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleInventoryClick.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleInventoryClose.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleInventoryEnchant.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleInventoryTransaction.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleMoveVehicle.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleSelectTrade.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleSteerBoat.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleSteerVehicle.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleUpdateSign.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleUseEntity.java
I'm looking at the diff between master and mcpenew, and trying to minimize it, from both sides.
This is a simple refactoring that breaks out the actual work of the constructor into a create() method, that can be independently called, for all middle blocks, which is needed by PSPE.
=> Refactor the MiddleBlocks to have a create() method, which is called by the constructor.

src/protocolsupport/listeners/InternalPluginMessageRequest.java, src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleSpecate.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_11_12r1_12r2/SpawnLiving.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_13/SpawnLiving.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_13/SpawnPainting.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_6_7/EntitySetAttributes.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_8/SpawnNamed.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_8_9r1_9r2_10_11_12r1_12r2_13/EntitySetAttributes.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_8_9r1_9r2_10_11_12r1_12r2_13/PlayerListSetEntry.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_9r1_9r2_10/SpawnLiving.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_9r1_9r2_10_11_12r1_12r2/SpawnPainting.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_9r1_9r2_10_11_12r1_12r2_13/BossBar.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_9r1_9r2_10_11_12r1_12r2_13/SpawnNamed.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_9r1_9r2_10_11_12r1_12r2_13/SpawnObject.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/CraftingData.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/PlayerListSetEntry.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnNamed.java, src/protocolsupport/protocol/serializer/MiscSerializer.java, src/protocolsupport/protocol/utils/datawatcher/objects/DataWatcherObjectOptionalUUID.java
Create PE-specific version of writeUUID, to remove PE-specific changes to non-PE code.
This was prompted by Shev's response in https://github.com/ProtocolSupport/ProtocolSupport/pull/982.
I'd like some feedback on the fix in "MiddleSpecate.java" (also! Someone should fix the typo of that class name!). I assume I can remove the ProtocolType check and just assume PC, but I'd like to hear someone confirm it. (I'm not sure really why the middle classes seem to be doing middleimpl stuff...)
With this patch, the diff between master and mcpenew outside PE files will be reduced (but not zero).
=> Create PE-specific version of writeUUID

resources/resources/pe/blockmapping.json, resources/resources/pe/itemmapping.json, src/protocolsupport/protocol/typeremapper/block/LegacyBlockData.java
Fix blue shulker box blocks, end rod orientations and pumpkin item remaps. Partial fix for mob heads (items work properly, blocks show up, but only as skeleton skulls).
=> Remap fixes.

resources/resources/pe/blockmapping.json, src/protocolsupport/protocol/typeremapper/pe/PEDataValues.java
More remap fixes:
Fix smooth quartz,smooth [red] sandstone and smooth stone blocks.
Fix squartz pillar blocks.
Fix snow golem, ghast fireball and blaze firecharge entity mappings.
=> More remap fixes

src/protocolsupport/protocol/utils/types/nbt/serializer/PENBTSerializer.java
The length needed to be an unsigned varint, not a signed.
=> Serializing of varint PE NBTs were wrong.

src/protocolsupport/zplatform/impl/pe/PEProxyServerInfoHandler.java
The unknown field in getServerInfo() in PEProxyServerInfoHandler is indeed some kind of ID. It must be unique per server instance, otherwise PE client will lump all servers on the LAN with the same ID together. Without this fix, it was not possible to run two different instances of PSPE on a LAN (and see them as separate).
=> Fix colliding servers

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/DeclareCommands.java, src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/StartGame.java, src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java, src/protocolsupport/protocol/typeremapper/pe/PEPacketIDs.java
This is done by reading and parsing the DeclareCommands packet from the PC server, and converting into the corresponding AVAILABLE_COMMANDS packet for PE. Most, but not all, functionality is kept.
=> Add support for tab completion on PE

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityTeleport.java
With this commit, now entities use relative movement so it is no longer buggy. Related to ProtocolSupport/ProtocolSupportPocketIssues#65.
=> Fixed strange behavior in mobs movement.

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_4_5_6_7_8_9r1_9r2_10_11_12r1_12r2/AbstractScoreboardTeam.java
This fixes an issue affecting users joining with 1.12.2 or earlier, to a server running the latest version with ProtocolSupport, where the last four characters of the scoreboard prefix were replaced with `§r§r`.
Before:
After:
=> Fix legacy scoreboard prefix having a reset appended twice
