src/protocolsupport/protocol/transformer/v_1_5/clientboundtransformer/LoginPacketTransformer.java
src/protocolsupport/protocol/transformer/v_1_6/clientboundtransformer/LoginPacketTransformer.java

Fixed:
[SaMEC] - При бане игрока в низкой версии не показывает что он забанен, пишет просто конец потока.

Fix ban message for 1.5.2-1.6.x

---

src/protocolsupport/protocol/transformer/v_1_5/clientboundtransformer/PlayPacketTransformer.java
src/protocolsupport/protocol/transformer/v_1_6/clientboundtransformer/PlayPacketTransformer.java

Fixed:
- Fixed weather conditions for 1.5.2 - 1.6.4

Raining fix

---

src/protocolsupport/protocol/transformer/v_1_5/clientboundtransformer/PlayPacketTransformer.java
src/protocolsupport/protocol/transformer/v_1_6/clientboundtransformer/PlayPacketTransformer.java
src/protocolsupport/utils/Utils.java

Fixed:
- [SPIGOT: efusion4] Except when I use 1.5.2 there is no sound when you hit people. Same with 1.6.2-1.6.4. 
Fix based on: <minecraft_folder>/assets/virtual/legacy/sounds.json

Fix sounds

---

src/protocolsupport/protocol/transformer/mcpe/utils/BlockIDRemapper.java

If not remapped, a invisible block is created on a MCPE client.
Also @Shevchik, good luck on the MCPE branch! It is progressing more and more with every commit, I remember way back, when I couldn't even connect with the MCPE branch, and now, I can connect and even interact with the world! Soon you will be able to *play* on a Bukkit Server with a MCPE client :smile:  :+1:

[MCPE] Remap Stained Glass (95) to Glass (20)

---

src/protocolsupport/protocol/typeremapper/id/IdRemapper.java

Remap Tall Plant to Yellow Flower for 1.6.X

---

src/protocolsupport/protocol/typeremapper/id/IdRemapper.java

[MCPE] Change Rabbit Remap

---

src/protocolsupport/protocol/typeremapper/id/IdRemapper.java
src/protocolsupport/protocol/typeremapper/id/RemappingRegistry.java

Change "Reigstry" to "Registry"

Fix Class Name Typo

---

src/protocolsupport/api/events/ServerPingResponseEvent.java
src/protocolsupport/commands/CommandHandler.java
src/protocolsupport/injector/network/BasicInjector.java
src/protocolsupport/injector/network/NettyInjector.java
src/protocolsupport/injector/network/ServerConnectionChannel.java
src/protocolsupport/protocol/packet/handler/AbstractHandshakeListener.java
src/protocolsupport/protocol/packet/handler/AbstractLoginListener.java
src/protocolsupport/protocol/packet/handler/PlayerLookupUUID.java
src/protocolsupport/protocol/packet/v_1_7/utils/ChatJsonConverter.java
src/protocolsupport/protocol/pipeline/initial/InitialPacketDecoder.java
src/protocolsupport/protocol/storage/ThrottleTracker.java
src/protocolsupport/protocol/typeremapper/id/IdRemapper.java
src/protocolsupport/utils/Utils.java

MinecraftServer.getServer() is deprecated, let's use something else
Also makes it easier to add Sponge Support ;)

Use Utils for getServer()

---

src/protocolsupport/protocol/packet/PEPacketIDs.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/BlockChangeSingle.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java

I made this just to learn how ProtocolSupport works.
It works(tm), but I still need to implement the BlockChangeMulti (MCPE doesn't have an equivalent for that due to BatchPackets)
I also need to figure out how to use those "flags" ( https://sel-project.github.io/sel-utils/pocket/101.html#play_update-block_flags-and-meta ) but it seems to work fine without them
(I placed those gravels and the stained clay using MC 1.11.2)

Add BlockChangeSingle for PE

---

.gitignore
src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleEntityAction.java
src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/PlayerAction.java

...what the title says. this adds sprint capabilities for the PE client.

PE Sprinting

---

src/protocolsupport/protocol/legacyremapper/pe/PELevelEvent.java
src/protocolsupport/protocol/legacyremapper/pe/PEPacketIDs.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/ChangeGameState.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Position.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java

Fixed the yaw clipping/jumping of pc clients' heads by applying a
constant.

Head Rotation + Weather Packets + Gamemode Update

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnGlobal.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java

Implemented lightning! =D
Easy, still, quite fun.

[PSPE] Lightning

---

src/protocolsupport/protocol/legacyremapper/pe/PEPacketIDs.java
src/protocolsupport/zplatform/pe/MCPEServer.java

Shifted a few IDs. (Due to pickblockrequest packet being implemented in new version.)

[PSPE] 1.0.5 support

---

src/protocolsupport/zplatform/pe/MCPEServer.java

@caspervanneck pointed out that that (even though it works already) it's better to also update the protocolversion.

[PSPE] Update protocolversion v1.0.5

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Title.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java
src/protocolsupport/protocol/typeremapper/pe/PEPacketIDs.java

Add Title packet for MCPE clients

---

src/protocolsupport/protocol/typeremapper/pe/PEDataValues.java

TODO: Check if the quartz slab -> nether brick slab and nether brick slab -> quartz slab is working properly, I don't know if that would cause an issue because the code swaps to the "same" data value...

Add more block remaps

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnPainting.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java
src/protocolsupport/protocol/typeremapper/pe/PEPacketIDs.java

Implement "SpawnPainting" packet

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityEffectAdd.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityEffectRemove.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java
src/protocolsupport/protocol/typeremapper/pe/PEPacketIDs.java

Implement "EntityEffectAdd" and "EntityEffectRemove" packets

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Login.java
src/protocolsupport/protocol/typeremapper/pe/PEPacketIDs.java

Note: This is only the resourcepack handshake (Faked 😉) and does not implement new sounds. But it does make the step and animal sounds work.
I believe @MrPowerGamerBR has a version of PlaySound wich should work after this and implement more sounds 😄

[PSPE] Fix sounds for PE players.

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityDestroy.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnObject.java
src/protocolsupport/protocol/serializer/ItemStackSerializer.java

[PSPE] [Patch] Stack patch

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/BlockBreakAnimation.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java
src/protocolsupport/protocol/typeremapper/pe/PELevelEvent.java

It's much hacking again but it works okay.
Not perfect. But okay.
Timing will never be perfect. Since we are kind of limited to ticks there will always be a change we're just hitting one tick off or maybe there's some network lagg. This will make it so the animation finishes too early or late. I think this is however the best we can do.

[PSPE] Break animations

---

src/protocolsupport/protocol/typeremapper/chunk/ChunkTransformerPE.java

[PSPE] Biomes

---

src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/Chat.java

https://sel-utils.github.io/protocol/pocket131/play/text

That unknown field is a unsigned byte, not a string

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/BlockTileUpdate.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java
src/protocolsupport/protocol/typeremapper/pe/PEPacketIDs.java
src/protocolsupport/protocol/typeremapper/tileentity/TileNBTRemapper.java

Thanks @MrPowerGamerBR 👍 
You can delete the branch in here if you like.

[PSPE] [Meta&Tiles] Remap sign tiles

---

src/protocolsupport/protocol/typeremapper/id/IdSkipper.java
src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/toclient/EnchantToPEEnchantSpecificRemapper.java

(Merging on mcpemeta because testing enchantments in mcpenew will be very hard)

Remap enchant IDs for MCPE and remap unknown enchants

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/InventoryOpen.java

Entity IDs are an signed varlong, not a varint (Fixes inventories)

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityEquipment.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java
src/protocolsupport/protocol/typeremapper/pe/PEPacketIDs.java
src/protocolsupport/protocol/utils/types/NetworkEntity.java

Implement "EntityEquipment" (held item and armor slots) for MCPE clients

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityEquipment.java

Add Off-hand slot in Mob Equipment Packet

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnNamed.java
src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/Chat.java
src/protocolsupport/protocol/typeremapper/pe/PEAdventureSettings.java
src/protocolsupport/zplatform/impl/PENetServerConstants.java

Yeah, IntelliJ IDEA loves shuffling the imports around, I need to figure out how to disable that.

Add missing fields, change protocol version, fix small typo

---

build.gradle
src/protocolsupport/api/chat/modifiers/HoverAction.java

Fixes all warnings in all of ProtocolSupport (makes me happy)
(Yes I just moved a supression, but this make the yellow symbol dissappear and that gives dopamine)

[Main] No more warnings

---

src/protocolsupport/protocol/typeremapper/tileentity/TileNBTRemapper.java
src/protocolsupport/protocol/utils/minecraftdata/MinecraftData.java

I don't like how I transform PC entity IDs to PE entity IDs but I'm not sure how I could transform it without doing that.

Remap Mob Spawner NBT tags for MCPE clients

---

src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/toclient/MonsterEggToPEIdSpecificRemapper.java

Remap spawn eggs for MCPE clients

---

src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/toclient/BookPagesToPESpecificRemapper.java

Add written book remapping for MCPE clients

---

src/protocolsupport/ProtocolSupport.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Login.java
src/protocolsupport/zplatform/pe/PECreativeInventory.java

Send creative inventory items to MCPE clients

---

src/protocolsupport/api/unsafe/peskins/PESkinsProvider.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/PlayerInfo.java

[PSPE] Check slimskin

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityStatus.java
src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/toclient/FireworkToPETagSpecificRemapper.java
src/protocolsupport/protocol/typeremapper/pe/PEDataValues.java
src/protocolsupport/protocol/typeremapper/watchedentity/remapper/SpecificRemapper.java
src/protocolsupport/protocol/utils/datawatcher/DataWatcherObjectIdRegistry.java
src/protocolsupport/zplatform/impl/glowstone/itemstack/GlowStoneNBTTagCompoundWrapper.java
src/protocolsupport/zplatform/impl/spigot/itemstack/SpigotNBTTagCompoundWrapper.java
src/protocolsupport/zplatform/itemstack/NBTTagCompoundWrapper.java

[PSPE] Fireworks

---

src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleSteerVehicle.java
src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/Interact.java

Update Interact packet, implement vehicle unmount

---

src/protocolsupport/protocol/packet/handler/AbstractHandshakeListener.java
src/protocolsupport/protocol/utils/spoofedata/PaperSpoofedDataParser.java
src/protocolsupport/protocol/utils/spoofedata/SpoofedData.java
src/protocolsupport/protocol/utils/spoofedata/SpoofedDataParser.java

Finally got some free time to PR a fix for the issue I submitted here: #739
Let me know if there are any changes needed. :)

Add support for Paper's PlayerHandshakeEvent

---

build.gradle
src/protocolsupport/zplatform/impl/glowstone/GlowStoneMiscUtils.java
src/protocolsupport/zplatform/impl/glowstone/GlowStonePacketFactory.java
src/protocolsupport/zplatform/impl/glowstone/network/GlowStoneNetworkManagerWrapper.java
src/protocolsupport/zplatform/impl/glowstone/network/handler/GlowStoneLoginListenerPlay.java

According to @DoppelnullYT, the fix seems to be working

Update Glowstone version, update code to match new Glowstone API, fixes #769

---

src/protocolsupport/ProtocolSupport.java
src/protocolsupport/listeners/PERequestListener.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Chunk.java
src/protocolsupport/zplatform/PlatformPacketFactory.java
src/protocolsupport/zplatform/impl/glowstone/GlowStonePacketFactory.java
src/protocolsupport/zplatform/impl/spigot/SpigotPacketFactory.java

WOOO
hack, but not so much extra memory or processing power

[PSPE] Fixed chunk issues.

---

src/protocolsupport/protocol/typeremapper/sound/SoundRemapper.java

Doesn't play hurt sound in <= 1.6

Add hit sound remap entry in <= 1.6

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_4_5_6/EntityTeleport.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_7/EntityTeleport.java

Should I refactor to v_4_5_6_7?

Fix minecart issue

---

src/protocolsupport/protocol/packet/handler/AbstractHandshakeListener.java
src/protocolsupport/protocol/pipeline/version/util/decoder/AbstractLegacyPacketDecoder.java
src/protocolsupport/protocol/pipeline/version/util/decoder/AbstractModernWithReorderPacketDecoder.java
src/protocolsupport/protocol/pipeline/version/v_1_8/PacketEncoder.java
src/protocolsupport/protocol/typeremapper/packet/AnimatePacketReorderer.java
src/protocolsupport/protocol/typeremapper/packet/ChunkSendIntervalPacketQueue.java
src/protocolsupport/zplatform/PlatformUtils.java
src/protocolsupport/zplatform/impl/glowstone/GlowStoneMiscUtils.java
src/protocolsupport/zplatform/impl/spigot/SpigotMiscUtils.java

(instead of claiming that the client is too new)

Give correct error message if a too old PE client tries to connect

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/InventoryData.java

Give correct update on brewing fuel consumption. This code is inspired by how Nukkit handles this. I have verified that it looks okay.

Give correct update on brewing fuel consumption.

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/InventoryData.java

Fixes cooking (which was twice the speed) and fuel consumption (which was not shown at all).

Fix updates on furnace interface

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityTeleport.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnLiving.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnObject.java

EntityMove and EntitySpawn packet updated. That's all of 1.5 protocol update.

PE 1.5 protocol update

---

src/protocolsupport/ProtocolSupport.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityLeash.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityStatus.java
src/protocolsupport/protocol/typeremapper/pe/PEDataValues.java

Fixes missing love/heart particles, totem of undying animation, etc. Will close PSPE#30.

Add proper remaps for entity status codes.

---

src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/MoveVehicle.java

Fix MoveVehicle.java

---

src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleInventoryOpen.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_4/InventoryOpen.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_5_6_7/InventoryOpen.java

When open the crafting table, current PS will send a inv title exactly "Unknown translation key: block.minecraft.crafting_table.name" to 1.4-1.7
Then 1.4~1.7 will validate the title size, crashes.
Refer issue: #889

Fix crafting table open error

---

src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/PreFlatteningItemIdData.java
src/protocolsupport/protocol/typeremapper/itemstack/complex/ItemStackComplexRemapperRegistry.java
src/protocolsupport/protocol/typeremapper/itemstack/complex/fromclient/ItemDurabilityFromLegacyDataComplexRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/complex/fromclient/MapFromLegacyIdComplexRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/complex/toclient/ItemDurabilityToLegacyDataComplexRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/complex/toclient/MapToLegacyIdComplexRemapper.java

Kind of band-aid, but this fixes issues such as #900 #905 with minimal changes.

[PATCH] Fix complex itemstack remapping.

---

src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleUpdateStructureBlock.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_13/UpdateStructureBlock.java
src/protocolsupport/protocol/packet/middleimpl/serverbound/play/abs_4_5_6_7_8_9r1_9r2_10_11_12r1_12r2/AbstractCustomPayload.java
src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_13/UpdateStructureBlock.java
src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_8_9r1_9r2_10_11_12r1_12r2/CustomPayload.java
src/protocolsupport/protocol/pipeline/version/v_1_13/PacketDecoder.java
src/protocolsupport/protocol/serializer/PositionSerializer.java
src/protocolsupport/protocol/typeremapper/legacy/LegacyCustomPayloadChannelName.java

Please test kthnxbye.
Should fix #914

Added structure block support.

---

src/protocolsupport/protocol/typeremapper/legacy/LegacyCustomPayloadChannelName.java

Fix sending messages to BungeeCord channel

---

src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleEntityEffectAdd.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_10_11_12r1_12r2_13/EntityEffectAdd.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_8_9r1_9r2/EntityEffectAdd.java
src/protocolsupport/protocol/pipeline/version/v_1_10/PacketEncoder.java
src/protocolsupport/protocol/pipeline/version/v_1_11/PacketEncoder.java
src/protocolsupport/protocol/pipeline/version/v_1_12/r1/PacketEncoder.java
src/protocolsupport/protocol/pipeline/version/v_1_12/r2/PacketEncoder.java
src/protocolsupport/protocol/pipeline/version/v_1_13/PacketEncoder.java
src/protocolsupport/protocol/pipeline/version/v_1_8/PacketEncoder.java
src/protocolsupport/protocol/pipeline/version/v_1_9/r1/PacketEncoder.java
src/protocolsupport/protocol/pipeline/version/v_1_9/r2/PacketEncoder.java

Fixes the effect display in the upper right edge of the client

Since 1.10 EntityEffectAdd has a flags bit field instead of a boolean

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_13/CustomPayload.java

ItemStacks in traders have changed too

Fix traders in 1.13 and 1.13.1

---

src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_8_9r1_9r2_10_11_12r1_12r2/CustomPayload.java

Fix PickItem

---

src/protocolsupport/protocol/typeremapper/legacy/LegacyCustomPayloadChannelName.java

This reverts commit 36b5b5db2b24b6ee11fbda1c136b0125c5a31dbe.
Fixes #940

Revert "Hopefully fix bungee channel."

---

src/protocolsupport/protocol/typeremapper/itemstack/complex/toclient/EmptyBookPageAdderComplexRemapper.java

Fixes writeable books showing no content

---

src/protocolsupport/protocol/typeremapper/block/LegacyBlockData.java

Bricks look completely out of place on old clients. Cobblestone looks a
bit better. Quartz would probably look better, but I imagine that both blocks need
to have the same hardness. (Bone & Cobble have a hardness of 2 while Quartz has
a hardness of 0.8)

Change Bone Block mapping to Cobblestone

---

resources/resources/pe/itemmapping.json

This solves the mapping issue for stained glass block items.

Fix peid for colored stained glass.

---

src/protocolsupport/protocol/typeremapper/chunk/BlockStorageWriterPE.java
src/protocolsupport/protocol/typeremapper/pe/PEBlocks.java
src/protocolsupport/zplatform/impl/pe/PEProxyServerInfoHandler.java
tests/protocolsupport/protocol/typeremapper/chunk/BlockStorageWriterPETest.java

Some FindBugs fixes seemed to have been lost in the splitup between master and mcpenew. 
Also make a better fix for BlockStorageWriterPE, and add a unit test (!) to verify functionality.

Some FindBugs fixes seemed to have been lost

---

resources/resources/pe/itemmapping.json

Automatically sorted and pretty-printed json using jq. Now it's easier to compare with block IDs.

Sort itemmapping in order by PEid, and then PEdata.

---

src/protocolsupport/zplatform/impl/pe/PECreativeInventory.java

This is not the complete, correct solution. As stated in the comment, that means parsing the base-64 formatted NBT tag. However, this stops the creative inventory from becoming spammed with enchanted books without enchantments, etc.

Make creative inventory look a bit less messed up.

---

.gitignore
src/protocolsupport/api/events/PlayerLoginStartEvent.java
src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleBlockTileUpdate.java
src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleEntitySetAttributes.java
src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleInventoryOpen.java
src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleChat.java
src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleSteerVehicle.java
src/protocolsupport/protocol/packet/middle/serverbound/play/MiddleUpdateSign.java
src/protocolsupport/protocol/serializer/MiscSerializer.java
src/protocolsupport/protocol/serializer/VarNumberSerializer.java
src/protocolsupport/protocol/storage/netcache/MovementCache.java
src/protocolsupport/protocol/typeremapper/block/LegacyBlockData.java
src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java
src/protocolsupport/protocol/utils/networkentity/NetworkEntityDataCache.java
src/protocolsupport/zplatform/PlatformPacketFactory.java
src/protocolsupport/zplatform/impl/glowstone/itemstack/GlowStoneNBTTagCompoundWrapper.java

I did a comparison between mcpenew and master, and tried to eliminate changes that was not needed. Mostly whitespace changes that caused unnecessary diffs, but also tried to make code a bit nicer, and more aligned with existing code in master.

Minor code changes to prepare mcpenew for integration into master.

---

build.gradle
src/protocolsupport/protocol/packet/handler/AbstractLoginListener.java
src/protocolsupport/protocol/packet/handler/AbstractLoginListenerPlay.java
src/protocolsupport/zplatform/impl/spigot/entitytracker/SpigotEntityTracker.java
src/protocolsupport/zplatform/impl/spigot/entitytracker/SpigotEntityTrackerEntry.java
src/protocolsupport/zplatform/impl/spigot/network/SpigotNetworkManagerWrapper.java
src/protocolsupport/zplatform/impl/spigot/network/handler/SpigotLoginListener.java
src/protocolsupport/zplatform/impl/spigot/network/handler/SpigotLoginListenerPlay.java
src/protocolsupport/zplatform/impl/spigot/network/pipeline/SpigotPacketCompressor.java

Untested because my computer is freezing like crazy
Updated Paper version, I also needed to rename `tick()` to `loginTick()` because `ITickable`'s method was renamed to... `tick()`

Updates due to Spigot's NMS changes

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnObject.java

This PR fix vector for shooting arrow and some others.

Fix spawn object yaw pitch

---

src/protocolsupport/protocol/typeremapper/itemstack/complex/fromclient/PotionFromPEIdRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/complex/toclient/PotionToPEIdSpecificRemapper.java

I'm not very sure that only tipped arrow is special.

Fix item data in tipped arrow

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityTeleport.java

Entity's yaw not correct after teleport.

Fix headYaw in EntityTeleport.java

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/ChangeDimension.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityTeleport.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SetPosition.java

Fixed player head movement if merged fix-movement branch

Fix player tp head rot

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityLeash.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityMetadata.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnLiving.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnNamed.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/SpawnPosition.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/StartGame.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/UseBed.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/VehiclePassengers.java
src/protocolsupport/protocol/pipeline/version/v_pe/PEPacketEncoder.java

This will fix https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/79.

Fix "sleepwalking" on PE.

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Animation.java
src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/UseBed.java

Added test that it os really the player themselves that are sleeping at UseBed. This triggered another bug, where it turned out to be important to send the corresponding wake-up sequence.

Fix sleeping in beds, properly this time.

---

src/protocolsupport/protocol/serializer/ItemStackSerializer.java
src/protocolsupport/protocol/serializer/MerchantDataSerializer.java
src/protocolsupport/protocol/utils/CommonNBT.java

(The critical part with the extra byte is thanks to Yesdog, the refactoring is my fault.)

Make trading great again.

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityMetadata.java
src/protocolsupport/protocol/typeremapper/entity/metadata/types/base/BaseEntityMetadataRemapper.java
src/protocolsupport/protocol/typeremapper/entity/metadata/types/special/PlayerEntityMetadataRemapper.java

(cherry picked from commit eaddb0c2917dbdf86ca0510b205e77506a8a0d43)
Player nametag fix, thanks to @MrPowerGamerBR !
Replaces #1036

[MCPE] player nametag fix

---

src/protocolsupport/protocol/typeremapper/pe/PEAdventureSettings.java

This is the menu in the chat UI with shortcuts for setting time, weather, and teleporting.

Make the "command shortcut menu" appear.

---

src/protocolsupport/api/ProtocolVersion.java
src/protocolsupport/listeners/FeatureEmulation.java
src/protocolsupport/protocol/packet/handler/AbstractLoginListener.java
src/protocolsupport/protocol/packet/handler/AbstractLoginListenerPlay.java
src/protocolsupport/protocol/pipeline/initial/InitialPacketDecoder.java
src/protocolsupport/protocol/serializer/ItemStackSerializer.java
src/protocolsupport/protocol/serializer/MerchantDataSerializer.java
src/protocolsupport/protocol/serializer/StringSerializer.java
src/protocolsupport/protocol/typeremapper/itemstack/ItemStackRemapper.java
src/protocolsupport/protocol/typeremapper/itemstack/complex/toclient/NBTStashRemapper.java

Remove isPC() and isPE().

---

src/protocolsupport/protocol/typeremapper/entity/metadata/types/base/BaseEntityMetadataRemapper.java

Fixes https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/98.

Fix missing swimming PE flag remap.

---

src/protocolsupport/protocol/typeremapper/tile/TileEntityRemapper.java

Partial fix for https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/72. (Only remaining issue is item is still white).

Fix banner colors on PE. (Blocks only, not items)

---

src/protocolsupport/protocol/typeremapper/itemstack/LegacyItemType.java

I found and fixed the issue! Also fixed red beds, which were plagued by the same problem.

Fix so banner items are not always white and bed items are not always red.

---

resources/resources/pe/blockmapping.json

Fix frosted ice remap.

---

resources/resources/pe/blockmapping.json

This fixes inverted daylight sensors on PE

Fix inverted daylight sensors not appearing on PE

---

src/protocolsupport/protocol/typeremapper/entity/metadata/types/base/BaseEntityMetadataRemapper.java
src/protocolsupport/protocol/typeremapper/entity/metadata/types/living/GiantEntityMetadataRemapper.java
src/protocolsupport/protocol/typeremapper/entity/metadata/types/living/SlimeEntityMetadataRemapper.java
src/protocolsupport/protocol/typeremapper/entity/metadata/types/living/ageable/RabbitEntityMetadataRemapper.java
src/protocolsupport/protocol/typeremapper/entity/metadata/types/living/zombie/ZombieEntityMetadataRemapper.java

Hello! I added a new metadata remap to send to clients the right size of rabbits. If another change is needed, or something can be done in a better way, don't hesitate to tell me.

Fixed rabbit size in PSPE

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/WorldEvent.java
src/protocolsupport/protocol/typeremapper/pe/PERecord.java

Adds the Jukebox popup for PE clients

Jukebox Popup

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/CustomPayload.java
src/protocolsupport/protocol/packet/middleimpl/serverbound/play/v_pe/CustomPayload.java

Apparently it *is* the varint version

[MCPE] Fix plugin message format

---

src/protocolsupport/protocol/typeremapper/basic/GenericIdSkipper.java

Ignore grindstone and loom for old clients

---

src/protocolsupport/listeners/FeatureEmulation.java

Fix doubled block place sound

---

src/protocolsupport/protocol/packet/middle/clientbound/play/MiddleBlockChangeSingle.java

Filter invalid block positions

---

src/protocolsupport/protocol/typeremapper/mapcolor/MapColorMappingRegistry.java
src/protocolsupport/protocol/typeremapper/mapcolor/ModernBaseMapColor.java

Map colors <1.17

---

src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_17r1_17r2/TitleClear.java

Fix TitleClear packet missing Reset field
